stages:
  - build
  - coverage

cache:
  paths:
    - subprojects/

variables:
  MESON_NOSAN_OPTIONS: "--buildtype=debug -Db_ndebug=false -Dbuild_tests=true -Dbuild_benchmarks=true"
  MESON_COMMON_OPTIONS: "--buildtype=debug -Db_ndebug=false -Dbuild_tests=true -Dbuild_benchmarks=true -Db_sanitize=address,undefined"

.build-template: &build-template
  stage: build
  artifacts:
    name: "matter-${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "build/meson-logs"

build:debian-gcc:
  image: registry.gitlab.com/dreyri/matter/debian:v4
  <<: *build-template
  script:
    - meson ${MESON_COMMON_OPTIONS} build
    - ninja -C build test

build:debian-clang:
  image: registry.gitlab.com/dreyri/matter/debian:v4
  <<: *build-template
  script:
    - CC=clang CXX=clang++ meson ${MESON_COMMON_OPTIONS} build
    - ninja -C build test

build:alpine:
  image: registry.gitlab.com/dreyri/matter/alpine:v1
  <<: *build-template
  script:
    - meson ${MESON_NOSAN_OPTIONS} build
    - ninja -C build test

coverage:
  image: registry.gitlab.com/dreyri/matter/debian:v4
  allow_failure: true
  stage: coverage
  script:
    - meson ${MESON_COMMON_OPTIONS} -Db_coverage=true build
    - ninja -C build test
    - ninja -C build coverage-text
  artifacts:
    paths:
      - build/meson-logs/coverage.txt
